name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js, npm and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Package for Windows
        if: matrix.os == 'windows-latest'
        run: |
          yarn build
          yarn pack:win

      - name: Package for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          yarn build
          yarn pack:linux

      - name: Package for MacOS
        if: matrix.os == 'macos-latest'
        run: |
          yarn build
          yarn pack:mac

      - name: Clean
        run: yarn clean:dist

      - name: Create a release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  createReleaseNote:
    runs-on: ubuntu-latest
    needs: [release]

    steps:
      - name: Set environment variables
        run: echo "VERSION=${GITHUB_REF##*/v}" >> $GITHUB_ENV

      - name: Create a release note
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: |
            ## âš ï¸ æ³¨æ„
            ãƒ€ã‚¦ãƒ³ãƒ­ãƒ¼ãƒ‰ã•ã‚Œã‚‹å‰ã« **å¿…ãš** [å…è²¬äº‹é …](https://github.com/${{ github.repository }}/blob/main/README.md#%EF%B8%8F-%E5%85%8D%E8%B2%AC%E4%BA%8B%E9%A0%85) ã‚’ãŠèª­ã¿ãã ã•ã„ã€‚
            ## ğŸ—‚ ãƒ•ã‚¡ã‚¤ãƒ«ã«ã¤ã„ã¦
            |OS|ãƒ•ã‚¡ã‚¤ãƒ«å|
            |-|-|
            |Windows (ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ©ãƒ¼)|serizawa-${{ env.VERSION }}.exe|
            |macOS|serizawa-${{ env.VERSION }}.dmg|
            |Liunx|serizawa-${{ env.VERSION }}.AppImage|
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
